name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100

    - name: Build
      run: dotnet build OfficeReestr.sln
    
    - name: Test
      run: dotnet test OfficeReestr.csproj